### ISSUE TITLE
new object property: is described in

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/SEPIO-ontology#1]
Need a way of connecting an ECO (inference) with a publication IAO instance.

Was thinking named InverseOf(ioa:isAbout)

Bit perhaps something constrained to be a domain of an ECO class would be better.

**Comment by cmungall** [comment]
SEPIO:0000124 'has supporting reference'
thanks @mbrush 

cc @kltm

**Comment by kltm** [comment]
Okay, I'll use this for the relation for geneontology/noctua#141 .
