### ISSUE TITLE
ClinVar  introduced MethodType "phenotyping only"

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/SEPIO-ontology#17]
Previously all (provided)  ClinVar accessions were typed as ```literature only``` 
and we tagged them with ```SEPIO:0000080```

with this release a new type appears in a half dozen instances  
(3 RCV & 3 SCV)  

     115657         <MethodType>literature only</MethodType>
          6         <MethodType>phenotyping only</MethodType>

I do not find and existing SEPIO term which seems appropriate for this new ClinVar method type. 

For reference the ClinVar accession with the new type are:   

- RCV000490816 
  - SCV000502994
- RCV000494689
  - SCV000579222
- RCV000494691
  - SCV000574694

**Comment by mbrush** [comment]
@TomConlin  - Thanks for the example records above - helped me understand what this new term is for.  

I added new class SEPIO_0000186 ('patient phenotyping study') to support these records. Closing issue.
