### ISSUE TITLE
Statement WIKI text sentence needs rewording.

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/SEPIO-ontology#18]
In the Statements wiki page within the [Scope & Usage Section](https://github.com/monarch-initiative/SEPIO-ontology/wiki/Statements#scope-and-usage) under item **1. Study Findings**, there is a sentence in the middle of the paragraph that reads poorly

_...
This does not mean **that the observations a Finding reports** are necessarily accurate reflections of reality - only that they were indeed made in a particular study.
..._

Please consider rewording.

**Comment by mbrush** [comment]
I updated text - if clear now i will close this ticket
