### ISSUE TITLE
PURL does not resolve

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/SEPIO-ontology#27]
SEPIO doesn't seem to be available at http://purl.obolibrary.org/obo/sepio.owl. Is this intentional?

**Comment by matentzn** [comment]
@mbrush I can fix this for you, AFAICS there is no purl config at all for sepio:

https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config

This might need updating too:
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/sepio.md

If you give me green light, I will take care of it :)

**Comment by matentzn** [comment]
@mbrush gentle ping :P Do you want me to fix it?

**Comment by mbrush** [comment]
HI Nico.  Thanks for the nudge. I'd be much obliged if you took case of this for me!  

Also, can you clarify the difference between the list of configs [here](https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology) where a sepio.md file exists, and the one [here](https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config) that contains yaml files and where there is no sepio config? I assume the latter is the place where I should add/update any config files for foundry ontologies going forward

**Comment by matentzn** [comment]
Hey Matt!

Ok, so the md file contains the metadata that is being displayed on the http://obofoundry.org/ website. No URL configuration happening there at all! 

I have now [created the PURL](https://github.com/OBOFoundry/purl.obolibrary.org/pull/565/files) config for SEPIO. Note that to make this future proof, I create official github releases for the [2017 version of sepio](https://github.com/monarch-initiative/SEPIO-ontology/blob/master/releases/2017-09-29/src/ontology/sepio.owl). Not the recently updated file in src/ontology/. Which is the current official sepio.owl file so I can release that instead? :) Talk soooon!

**Comment by matentzn** [comment]
Closed via https://github.com/OBOFoundry/purl.obolibrary.org/pull/565/files
