### ISSUE TITLE
License info disparity

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/SEPIO-ontology#31]
License info for SEPIO in `README.md` says Creative Commons 3.0 BY: 
```
License
The SEPIO Ontology and Framework is an open source project, free to re-use and re-mix under a Creative Commons 3.0 BY license.
```
By the link in said text links to Creative Commons 2.0 BY
(i.e. https://creativecommons.org/licenses/by/2.0/)

**Comment by matentzn** [comment]
Thanks Justin, fixed.

**Comment by justaddcoffee** [comment]
+1
