### ISSUE TITLE
Version string is not formatted into sepio-merged.owl

### ISSUE THREAD

**Issue by cthoyt** [monarch-initiative/SEPIO-ontology#34]
https://www.ebi.ac.uk/ols/ontologies/sepio is reporting the version for SEPIO is `$Revision$`.
<img width="425" alt="Screen Shot 2021-01-25 at 14 45 35" src="https://user-images.githubusercontent.com/5069736/105713926-fd199500-5f1b-11eb-9f75-783fac830fcc.png">

The offending line seems to be

https://github.com/monarch-initiative/SEPIO-ontology/blob/127adceb2bb02b60c2950b4eda4914740b057bd6/src/ontology/sepio-merged.owl#L68

I guess this is a place where a value should be automatically added. Version information doesn't seem to appear in either https://github.com/monarch-initiative/SEPIO-ontology/blob/master/src/ontology/sepio-valueset.owl nor https://github.com/monarch-initiative/SEPIO-ontology/blob/master/src/ontology/sepio.owl.

**Comment by cmungall** [comment]
@mbrush - seems like an easy fix

Did we really maintain sepio in SVN at one point :-)?

Note ODK should now have standard release procedures for both versionInfo and versionIRI

**Comment by cthoyt** [comment]
@cmungall there's lots of evidence of the SVN days of the OBO community scattered throughout the various OBO documents, including several places in http://www.obofoundry.org/registry/ontologies.yml
