### ISSUE TITLE
What is the development status of SEPIO?

### ISSUE THREAD

**Issue by StroemPhi** [monarch-initiative/SEPIO-ontology#37]
Dear SEPIO team, 

for my ongoing work in the [Academic Event Ontology](https://github.com/tibonto/aeon) I was looking into SEPIO, hoping to find terms and relations I could reuse for the modeling of contributions to academic events (planned processes).  But from looking at the open issues and last commits, it seems as if this repo is not really worked on anymore. Am I correct with this assumtion?

**Comment by matentzn** [comment]
SEPIO is in low maintenance mode atm, I have recently obtained edit rights on the repo to create releases. We can handle a lightweight alignment if this of interest to you @StroemPhi

**Comment by StroemPhi** [comment]
Thanks for the info @matentzn! I'm not really sure if SEPIO is what I need in [AEON](https://github.com/tibonto/aeon/), or if CRO is better suited for my needs to model various types of contributions to academic event, as it has many destinct contributor roles. I just saw, when researching "contributor role" in the CRO issues, that there is some kind of overlap between SEPIO and CRO which confuses me.

**Comment by matentzn** [comment]
I dont know anything about the contents of either, sorry. I think you can try to reach out to @mbrush - I think he is involved in both somehow.
